version: "3.0"

services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - "8001:80"
        volumes:
            - ./:/var/www
            - ./teaching.conf:/etc/nginx/conf.d/default.conf
        # depends_on:
        #     mysql
        working_dir: /var/www
    # mysql:
    #     image: mysql
    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www
